<?xml version="1.0" encoding="UTF-8"?>
<testsuite xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="https://maven.apache.org/surefire/maven-surefire-plugin/xsd/surefire-test-report-3.0.xsd" version="3.0" name="com.mycompany.solucao1.GestorDesportivo_ESTest" time="0.078" tests="95" errors="9" skipped="0" failures="15">
  <properties>
    <property name="sun.desktop" value="gnome"/>
    <property name="awt.toolkit" value="sun.awt.X11.XToolkit"/>
    <property name="file.encoding.pkg" value="sun.io"/>
    <property name="java.specification.version" value="1.8"/>
    <property name="sun.cpu.isalist" value=""/>
    <property name="sun.jnu.encoding" value="UTF-8"/>
    <property name="java.class.path" value="/home/tomas/LEI/3ANO/2SEM/ATS/ATS/EvoSuiteJacoco/Solucao1/target/test-classes:/home/tomas/LEI/3ANO/2SEM/ATS/ATS/EvoSuiteJacoco/Solucao1/target/classes:/home/tomas/.m2/repository/org/junit/jupiter/junit-jupiter/5.9.2/junit-jupiter-5.9.2.jar:/home/tomas/.m2/repository/org/junit/jupiter/junit-jupiter-params/5.9.2/junit-jupiter-params-5.9.2.jar:/home/tomas/.m2/repository/org/junit/jupiter/junit-jupiter-engine/5.9.2/junit-jupiter-engine-5.9.2.jar:/home/tomas/.m2/repository/org/junit/jupiter/junit-jupiter-api/5.9.2/junit-jupiter-api-5.9.2.jar:/home/tomas/.m2/repository/org/opentest4j/opentest4j/1.2.0/opentest4j-1.2.0.jar:/home/tomas/.m2/repository/org/junit/platform/junit-platform-commons/1.9.2/junit-platform-commons-1.9.2.jar:/home/tomas/.m2/repository/org/apiguardian/apiguardian-api/1.1.2/apiguardian-api-1.1.2.jar:/home/tomas/.m2/repository/junit/junit/4.12/junit-4.12.jar:/home/tomas/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar:/home/tomas/.m2/repository/org/junit/vintage/junit-vintage-engine/5.9.1/junit-vintage-engine-5.9.1.jar:/home/tomas/.m2/repository/org/junit/platform/junit-platform-engine/1.9.2/junit-platform-engine-1.9.2.jar:/home/tomas/.m2/repository/org/evosuite/evosuite-standalone-runtime/1.0.6/evosuite-standalone-runtime-1.0.6.jar:"/>
    <property name="java.vm.vendor" value="Private Build"/>
    <property name="sun.arch.data.model" value="64"/>
    <property name="java.vendor.url" value="http://java.oracle.com/"/>
    <property name="user.timezone" value=""/>
    <property name="java.vm.specification.version" value="1.8"/>
    <property name="os.name" value="Linux"/>
    <property name="user.country" value="PT"/>
    <property name="sun.java.launcher" value="SUN_STANDARD"/>
    <property name="sun.boot.library.path" value="/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64"/>
    <property name="sun.java.command" value="/home/tomas/LEI/3ANO/2SEM/ATS/ATS/EvoSuiteJacoco/Solucao1/target/surefire/surefirebooter1244230477523540473.jar /home/tomas/LEI/3ANO/2SEM/ATS/ATS/EvoSuiteJacoco/Solucao1/target/surefire 2025-06-04T21-01-38_003-jvmRun1 surefire9157478073374163302tmp surefire_01421752035635430700tmp"/>
    <property name="surefire.test.class.path" value="/home/tomas/LEI/3ANO/2SEM/ATS/ATS/EvoSuiteJacoco/Solucao1/target/test-classes:/home/tomas/LEI/3ANO/2SEM/ATS/ATS/EvoSuiteJacoco/Solucao1/target/classes:/home/tomas/.m2/repository/org/junit/jupiter/junit-jupiter/5.9.2/junit-jupiter-5.9.2.jar:/home/tomas/.m2/repository/org/junit/jupiter/junit-jupiter-params/5.9.2/junit-jupiter-params-5.9.2.jar:/home/tomas/.m2/repository/org/junit/jupiter/junit-jupiter-engine/5.9.2/junit-jupiter-engine-5.9.2.jar:/home/tomas/.m2/repository/org/junit/jupiter/junit-jupiter-api/5.9.2/junit-jupiter-api-5.9.2.jar:/home/tomas/.m2/repository/org/opentest4j/opentest4j/1.2.0/opentest4j-1.2.0.jar:/home/tomas/.m2/repository/org/junit/platform/junit-platform-commons/1.9.2/junit-platform-commons-1.9.2.jar:/home/tomas/.m2/repository/org/apiguardian/apiguardian-api/1.1.2/apiguardian-api-1.1.2.jar:/home/tomas/.m2/repository/junit/junit/4.12/junit-4.12.jar:/home/tomas/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar:/home/tomas/.m2/repository/org/junit/vintage/junit-vintage-engine/5.9.1/junit-vintage-engine-5.9.1.jar:/home/tomas/.m2/repository/org/junit/platform/junit-platform-engine/1.9.2/junit-platform-engine-1.9.2.jar:/home/tomas/.m2/repository/org/evosuite/evosuite-standalone-runtime/1.0.6/evosuite-standalone-runtime-1.0.6.jar:"/>
    <property name="sun.cpu.endian" value="little"/>
    <property name="user.home" value="/home/tomas"/>
    <property name="user.language" value="pt"/>
    <property name="java.specification.vendor" value="Oracle Corporation"/>
    <property name="java.home" value="/usr/lib/jvm/java-8-openjdk-amd64/jre"/>
    <property name="basedir" value="/home/tomas/LEI/3ANO/2SEM/ATS/ATS/EvoSuiteJacoco/Solucao1"/>
    <property name="file.separator" value="/"/>
    <property name="line.separator" value="&#10;"/>
    <property name="java.vm.specification.vendor" value="Oracle Corporation"/>
    <property name="java.specification.name" value="Java Platform API Specification"/>
    <property name="java.awt.graphicsenv" value="sun.awt.X11GraphicsEnvironment"/>
    <property name="surefire.real.class.path" value="/home/tomas/LEI/3ANO/2SEM/ATS/ATS/EvoSuiteJacoco/Solucao1/target/surefire/surefirebooter1244230477523540473.jar:/home/tomas/.m2/repository/org/jacoco/org.jacoco.agent/0.8.8/org.jacoco.agent-0.8.8-runtime.jar"/>
    <property name="sun.boot.class.path" value="/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/resources.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/rt.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/sunrsasign.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/jsse.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/jce.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/charsets.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/jfr.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/classes"/>
    <property name="sun.management.compiler" value="HotSpot 64-Bit Tiered Compilers"/>
    <property name="java.runtime.version" value="1.8.0_452-8u452-ga~us1-0ubuntu1~22.04-b09"/>
    <property name="user.name" value="tomas"/>
    <property name="path.separator" value=":"/>
    <property name="os.version" value="6.8.0-60-generic"/>
    <property name="java.endorsed.dirs" value="/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/endorsed"/>
    <property name="java.runtime.name" value="OpenJDK Runtime Environment"/>
    <property name="file.encoding" value="UTF-8"/>
    <property name="java.vm.name" value="OpenJDK 64-Bit Server VM"/>
    <property name="localRepository" value="/home/tomas/.m2/repository"/>
    <property name="java.vendor.url.bug" value="http://bugreport.sun.com/bugreport/"/>
    <property name="java.io.tmpdir" value="/tmp"/>
    <property name="java.version" value="1.8.0_452"/>
    <property name="user.dir" value="/home/tomas/LEI/3ANO/2SEM/ATS/ATS/EvoSuiteJacoco/Solucao1"/>
    <property name="os.arch" value="amd64"/>
    <property name="java.vm.specification.name" value="Java Virtual Machine Specification"/>
    <property name="java.awt.printerjob" value="sun.print.PSPrinterJob"/>
    <property name="sun.os.patch.level" value="unknown"/>
    <property name="java.library.path" value=":/usr/java/packages/lib/amd64:/usr/lib/x86_64-linux-gnu/jni:/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu:/usr/lib/jni:/lib:/usr/lib"/>
    <property name="java.vm.info" value="mixed mode"/>
    <property name="java.vendor" value="Private Build"/>
    <property name="java.vm.version" value="25.452-b09"/>
    <property name="java.specification.maintenance.version" value="6"/>
    <property name="java.ext.dirs" value="/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext:/usr/java/packages/lib/ext"/>
    <property name="sun.io.unicode.encoding" value="UnicodeLittle"/>
    <property name="java.class.version" value="52.0"/>
    <property name="use_separate_classloader" value="false"/>
  </properties>
  <testcase name="test16" classname="com.mycompany.solucao1.GestorDesportivo_ESTest" time="0.001"/>
  <testcase name="test15" classname="com.mycompany.solucao1.GestorDesportivo_ESTest" time="0"/>
  <testcase name="test59" classname="com.mycompany.solucao1.GestorDesportivo_ESTest" time="0.001">
    <failure message="expected:&lt;2&gt; but was:&lt;7&gt;" type="java.lang.AssertionError"><![CDATA[java.lang.AssertionError: expected:<2> but was:<7>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.mycompany.solucao1.GestorDesportivo_ESTest.test59(GestorDesportivo_ESTest.java:837)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:750)
]]></failure>
  </testcase>
  <testcase name="test14" classname="com.mycompany.solucao1.GestorDesportivo_ESTest" time="0.003"/>
  <testcase name="test58" classname="com.mycompany.solucao1.GestorDesportivo_ESTest" time="0.001">
    <failure message="expected:&lt;1&gt; but was:&lt;8&gt;" type="java.lang.AssertionError"><![CDATA[java.lang.AssertionError: expected:<1> but was:<8>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.mycompany.solucao1.GestorDesportivo_ESTest.test58(GestorDesportivo_ESTest.java:828)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:750)
]]></failure>
  </testcase>
  <testcase name="test13" classname="com.mycompany.solucao1.GestorDesportivo_ESTest" time="0.001"/>
  <testcase name="test57" classname="com.mycompany.solucao1.GestorDesportivo_ESTest" time="0"/>
  <testcase name="test12" classname="com.mycompany.solucao1.GestorDesportivo_ESTest" time="0.001"/>
  <testcase name="test56" classname="com.mycompany.solucao1.GestorDesportivo_ESTest" time="0.001"/>
  <testcase name="test11" classname="com.mycompany.solucao1.GestorDesportivo_ESTest" time="0"/>
  <testcase name="test55" classname="com.mycompany.solucao1.GestorDesportivo_ESTest" time="0.001"/>
  <testcase name="test10" classname="com.mycompany.solucao1.GestorDesportivo_ESTest" time="0"/>
  <testcase name="test54" classname="com.mycompany.solucao1.GestorDesportivo_ESTest" time="0.001"/>
  <testcase name="test53" classname="com.mycompany.solucao1.GestorDesportivo_ESTest" time="0"/>
  <testcase name="test19" classname="com.mycompany.solucao1.GestorDesportivo_ESTest" time="0.001">
    <error type="java.lang.NullPointerException"><![CDATA[java.lang.NullPointerException
	at com.mycompany.solucao1.GestorDesportivo.kmsPercorridos(GestorDesportivo.java:306)
	at com.mycompany.solucao1.GestorDesportivo_ESTest.test19(GestorDesportivo_ESTest.java:277)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:750)
]]></error>
  </testcase>
  <testcase name="test18" classname="com.mycompany.solucao1.GestorDesportivo_ESTest" time="0.001"/>
  <testcase name="test17" classname="com.mycompany.solucao1.GestorDesportivo_ESTest" time="0.001"/>
  <testcase name="test52" classname="com.mycompany.solucao1.GestorDesportivo_ESTest" time="0">
    <error type="java.lang.NullPointerException"><![CDATA[java.lang.NullPointerException
	at com.mycompany.solucao1.GestorDesportivo.atividadesExecutadasUtilizador(GestorDesportivo.java:315)
	at com.mycompany.solucao1.GestorDesportivo_ESTest.test52(GestorDesportivo_ESTest.java:730)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:750)
]]></error>
  </testcase>
  <testcase name="test51" classname="com.mycompany.solucao1.GestorDesportivo_ESTest" time="0">
    <error type="java.lang.NullPointerException"><![CDATA[java.lang.NullPointerException
	at com.mycompany.solucao1.Corrida.geraAtividade(Corrida.java:58)
	at com.mycompany.solucao1.PlanoTreino.geraPlanoTreino(PlanoTreino.java:238)
	at com.mycompany.solucao1.GestorDesportivo.geraPlanoTreinoUtilizador(GestorDesportivo.java:449)
	at com.mycompany.solucao1.GestorDesportivo_ESTest.test51(GestorDesportivo_ESTest.java:718)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:750)
]]></error>
    <system-out><![CDATA[Ok

]]></system-out>
  </testcase>
  <testcase name="test50" classname="com.mycompany.solucao1.GestorDesportivo_ESTest" time="0.001"/>
  <testcase name="test94" classname="com.mycompany.solucao1.GestorDesportivo_ESTest" time="0.006"/>
  <testcase name="test93" classname="com.mycompany.solucao1.GestorDesportivo_ESTest" time="0"/>
  <testcase name="test92" classname="com.mycompany.solucao1.GestorDesportivo_ESTest" time="0.001"/>
  <testcase name="test91" classname="com.mycompany.solucao1.GestorDesportivo_ESTest" time="0.002"/>
  <testcase name="test90" classname="com.mycompany.solucao1.GestorDesportivo_ESTest" time="0.001"/>
  <testcase name="test05" classname="com.mycompany.solucao1.GestorDesportivo_ESTest" time="0">
    <failure message="expected:&lt;1&gt; but was:&lt;19&gt;" type="java.lang.AssertionError"><![CDATA[java.lang.AssertionError: expected:<1> but was:<19>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.mycompany.solucao1.GestorDesportivo_ESTest.test05(GestorDesportivo_ESTest.java:133)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:750)
]]></failure>
  </testcase>
  <testcase name="test49" classname="com.mycompany.solucao1.GestorDesportivo_ESTest" time="0.001">
    <failure message="expected:&lt;...digo de Utilizador: [1&#10;Nome: gcNB0%{e.}E2wnrh&#10;Morada: gcNB0%{e.}E2wnrh&#10;Email: gcNB0%{e.}E2wnrh&#10;Frequencia Cardiaca: -17 bpm&#10;Peso: -17.0 kilos&#10;Altura: -17 centimetros&#10;Data de nascimento 14/02/2014&#10;Idade: 0] anos&#10;Genero: -&#10;Ativ...&gt; but was:&lt;...digo de Utilizador: [-2487&#10;Nome: gcNB0%{e.}E2wnrh&#10;Morada: gcNB0%{e.}E2wnrh&#10;Email: gcNB0%{e.}E2wnrh&#10;Frequencia Cardiaca: -17 bpm&#10;Peso: -17.0 kilos&#10;Altura: -17 centimetros&#10;Data de nascimento 14/02/2014&#10;Idade: 11] anos&#10;Genero: -&#10;Ativ...&gt;" type="org.junit.ComparisonFailure"><![CDATA[org.junit.ComparisonFailure: 
expected:<...digo de Utilizador: [1
Nome: gcNB0%{e.}E2wnrh
Morada: gcNB0%{e.}E2wnrh
Email: gcNB0%{e.}E2wnrh
Frequencia Cardiaca: -17 bpm
Peso: -17.0 kilos
Altura: -17 centimetros
Data de nascimento 14/02/2014
Idade: 0] anos
Genero: -
Ativ...> but was:<...digo de Utilizador: [-2487
Nome: gcNB0%{e.}E2wnrh
Morada: gcNB0%{e.}E2wnrh
Email: gcNB0%{e.}E2wnrh
Frequencia Cardiaca: -17 bpm
Peso: -17.0 kilos
Altura: -17 centimetros
Data de nascimento 14/02/2014
Idade: 11] anos
Genero: -
Ativ...>
	at org.junit.Assert.assertEquals(Assert.java:115)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at com.mycompany.solucao1.GestorDesportivo_ESTest.test49(GestorDesportivo_ESTest.java:702)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:750)
]]></failure>
  </testcase>
  <testcase name="test04" classname="com.mycompany.solucao1.GestorDesportivo_ESTest" time="0.001">
    <failure message="expected:&lt;1&gt; but was:&lt;20&gt;" type="java.lang.AssertionError"><![CDATA[java.lang.AssertionError: expected:<1> but was:<20>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.mycompany.solucao1.GestorDesportivo_ESTest.test04(GestorDesportivo_ESTest.java:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:750)
]]></failure>
  </testcase>
  <testcase name="test48" classname="com.mycompany.solucao1.GestorDesportivo_ESTest" time="0"/>
  <testcase name="test03" classname="com.mycompany.solucao1.GestorDesportivo_ESTest" time="0"/>
  <testcase name="test47" classname="com.mycompany.solucao1.GestorDesportivo_ESTest" time="0"/>
  <testcase name="test02" classname="com.mycompany.solucao1.GestorDesportivo_ESTest" time="0.001"/>
  <testcase name="test46" classname="com.mycompany.solucao1.GestorDesportivo_ESTest" time="0"/>
  <testcase name="test01" classname="com.mycompany.solucao1.GestorDesportivo_ESTest" time="0.001"/>
  <testcase name="test45" classname="com.mycompany.solucao1.GestorDesportivo_ESTest" time="0"/>
  <testcase name="test89" classname="com.mycompany.solucao1.GestorDesportivo_ESTest" time="0"/>
  <testcase name="test00" classname="com.mycompany.solucao1.GestorDesportivo_ESTest" time="0.001"/>
  <testcase name="test44" classname="com.mycompany.solucao1.GestorDesportivo_ESTest" time="0"/>
  <testcase name="test88" classname="com.mycompany.solucao1.GestorDesportivo_ESTest" time="0.001"/>
  <testcase name="test43" classname="com.mycompany.solucao1.GestorDesportivo_ESTest" time="0"/>
  <testcase name="test87" classname="com.mycompany.solucao1.GestorDesportivo_ESTest" time="0.001"/>
  <testcase name="test42" classname="com.mycompany.solucao1.GestorDesportivo_ESTest" time="0"/>
  <testcase name="test86" classname="com.mycompany.solucao1.GestorDesportivo_ESTest" time="0"/>
  <testcase name="test09" classname="com.mycompany.solucao1.GestorDesportivo_ESTest" time="0.001"/>
  <testcase name="test08" classname="com.mycompany.solucao1.GestorDesportivo_ESTest" time="0"/>
  <testcase name="test07" classname="com.mycompany.solucao1.GestorDesportivo_ESTest" time="0.001"/>
  <testcase name="test06" classname="com.mycompany.solucao1.GestorDesportivo_ESTest" time="0">
    <error type="java.lang.NullPointerException"><![CDATA[java.lang.NullPointerException
	at com.mycompany.solucao1.GestorDesportivo.registaPlanoTreino(GestorDesportivo.java:296)
	at com.mycompany.solucao1.GestorDesportivo_ESTest.test06(GestorDesportivo_ESTest.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:750)
]]></error>
  </testcase>
  <testcase name="test41" classname="com.mycompany.solucao1.GestorDesportivo_ESTest" time="0.001"/>
  <testcase name="test85" classname="com.mycompany.solucao1.GestorDesportivo_ESTest" time="0"/>
  <testcase name="test40" classname="com.mycompany.solucao1.GestorDesportivo_ESTest" time="0.001"/>
  <testcase name="test84" classname="com.mycompany.solucao1.GestorDesportivo_ESTest" time="0">
    <error type="java.lang.NullPointerException"><![CDATA[java.lang.NullPointerException
	at com.mycompany.solucao1.GestorDesportivo.estadoAtualizado(GestorDesportivo.java:53)
	at com.mycompany.solucao1.GestorDesportivo_ESTest.test84(GestorDesportivo_ESTest.java:1064)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:750)
]]></error>
  </testcase>
  <testcase name="test83" classname="com.mycompany.solucao1.GestorDesportivo_ESTest" time="0.001">
    <error type="java.lang.NullPointerException"><![CDATA[java.lang.NullPointerException
	at com.mycompany.solucao1.GestorDesportivo.estadoAtualizado(GestorDesportivo.java:57)
	at com.mycompany.solucao1.GestorDesportivo_ESTest.test83(GestorDesportivo_ESTest.java:1057)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:750)
]]></error>
  </testcase>
  <testcase name="test82" classname="com.mycompany.solucao1.GestorDesportivo_ESTest" time="0.001"/>
  <testcase name="test81" classname="com.mycompany.solucao1.GestorDesportivo_ESTest" time="0">
    <error type="java.lang.NullPointerException"><![CDATA[java.lang.NullPointerException
	at com.mycompany.solucao1.GestorDesportivo.metrosAltimetria(GestorDesportivo.java:310)
	at com.mycompany.solucao1.GestorDesportivo_ESTest.test81(GestorDesportivo_ESTest.java:1040)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:750)
]]></error>
  </testcase>
  <testcase name="test80" classname="com.mycompany.solucao1.GestorDesportivo_ESTest" time="0"/>
  <testcase name="test38" classname="com.mycompany.solucao1.GestorDesportivo_ESTest" time="0.001"/>
  <testcase name="test37" classname="com.mycompany.solucao1.GestorDesportivo_ESTest" time="0"/>
  <testcase name="test36" classname="com.mycompany.solucao1.GestorDesportivo_ESTest" time="0.001"/>
  <testcase name="test35" classname="com.mycompany.solucao1.GestorDesportivo_ESTest" time="0.001"/>
  <testcase name="test79" classname="com.mycompany.solucao1.GestorDesportivo_ESTest" time="0.001"/>
  <testcase name="test34" classname="com.mycompany.solucao1.GestorDesportivo_ESTest" time="0"/>
  <testcase name="test78" classname="com.mycompany.solucao1.GestorDesportivo_ESTest" time="0.001"/>
  <testcase name="test33" classname="com.mycompany.solucao1.GestorDesportivo_ESTest" time="0.003"/>
  <testcase name="test77" classname="com.mycompany.solucao1.GestorDesportivo_ESTest" time="0">
    <error type="java.lang.NullPointerException"><![CDATA[java.lang.NullPointerException
	at com.mycompany.solucao1.GestorDesportivo.atividadesUtilizador(GestorDesportivo.java:323)
	at com.mycompany.solucao1.GestorDesportivo_ESTest.test77(GestorDesportivo_ESTest.java:999)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:750)
]]></error>
  </testcase>
  <testcase name="test32" classname="com.mycompany.solucao1.GestorDesportivo_ESTest" time="0.001"/>
  <testcase name="test76" classname="com.mycompany.solucao1.GestorDesportivo_ESTest" time="0.001">
    <failure message="expected:&lt;1&gt; but was:&lt;-2479&gt;" type="java.lang.AssertionError"><![CDATA[java.lang.AssertionError: expected:<1> but was:<-2479>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.mycompany.solucao1.GestorDesportivo_ESTest.test76(GestorDesportivo_ESTest.java:992)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:750)
]]></failure>
  </testcase>
  <testcase name="test31" classname="com.mycompany.solucao1.GestorDesportivo_ESTest" time="0"/>
  <testcase name="test75" classname="com.mycompany.solucao1.GestorDesportivo_ESTest" time="0.001"/>
  <testcase name="test39" classname="com.mycompany.solucao1.GestorDesportivo_ESTest" time="0.001"/>
  <testcase name="test30" classname="com.mycompany.solucao1.GestorDesportivo_ESTest" time="0"/>
  <testcase name="test74" classname="com.mycompany.solucao1.GestorDesportivo_ESTest" time="0.001">
    <failure message="Expecting exception: NullPointerException" type="java.lang.AssertionError"><![CDATA[java.lang.AssertionError: Expecting exception: NullPointerException
	at org.junit.Assert.fail(Assert.java:88)
	at com.mycompany.solucao1.GestorDesportivo_ESTest.test74(GestorDesportivo_ESTest.java:971)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:750)
]]></failure>
  </testcase>
  <testcase name="test73" classname="com.mycompany.solucao1.GestorDesportivo_ESTest" time="0.001"/>
  <testcase name="test72" classname="com.mycompany.solucao1.GestorDesportivo_ESTest" time="0">
    <failure message="Expecting exception: NullPointerException" type="java.lang.AssertionError"><![CDATA[java.lang.AssertionError: Expecting exception: NullPointerException
	at org.junit.Assert.fail(Assert.java:88)
	at com.mycompany.solucao1.GestorDesportivo_ESTest.test72(GestorDesportivo_ESTest.java:947)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:750)
]]></failure>
  </testcase>
  <testcase name="test71" classname="com.mycompany.solucao1.GestorDesportivo_ESTest" time="0.001"/>
  <testcase name="test70" classname="com.mycompany.solucao1.GestorDesportivo_ESTest" time="0"/>
  <testcase name="test27" classname="com.mycompany.solucao1.GestorDesportivo_ESTest" time="0.001">
    <system-out><![CDATA[Ok

]]></system-out>
  </testcase>
  <testcase name="test26" classname="com.mycompany.solucao1.GestorDesportivo_ESTest" time="0"/>
  <testcase name="test25" classname="com.mycompany.solucao1.GestorDesportivo_ESTest" time="0.001"/>
  <testcase name="test69" classname="com.mycompany.solucao1.GestorDesportivo_ESTest" time="0.001">
    <failure type="java.lang.AssertionError"><![CDATA[java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at com.mycompany.solucao1.GestorDesportivo_ESTest.test69(GestorDesportivo_ESTest.java:922)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:750)
]]></failure>
  </testcase>
  <testcase name="test24" classname="com.mycompany.solucao1.GestorDesportivo_ESTest" time="0.001"/>
  <testcase name="test68" classname="com.mycompany.solucao1.GestorDesportivo_ESTest" time="0"/>
  <testcase name="test23" classname="com.mycompany.solucao1.GestorDesportivo_ESTest" time="0.001"/>
  <testcase name="test67" classname="com.mycompany.solucao1.GestorDesportivo_ESTest" time="0.001">
    <failure type="java.lang.AssertionError"><![CDATA[java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at com.mycompany.solucao1.GestorDesportivo_ESTest.test67(GestorDesportivo_ESTest.java:907)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:750)
]]></failure>
  </testcase>
  <testcase name="test22" classname="com.mycompany.solucao1.GestorDesportivo_ESTest" time="0.001">
    <error type="java.lang.NullPointerException"><![CDATA[java.lang.NullPointerException
	at com.mycompany.solucao1.Corrida.geraAtividade(Corrida.java:58)
	at com.mycompany.solucao1.PlanoTreino.geraPlanoTreino(PlanoTreino.java:238)
	at com.mycompany.solucao1.GestorDesportivo.geraPlanoTreinoUtilizador(GestorDesportivo.java:449)
	at com.mycompany.solucao1.GestorDesportivo_ESTest.test22(GestorDesportivo_ESTest.java:323)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:750)
]]></error>
    <system-out><![CDATA[Ok

]]></system-out>
  </testcase>
  <testcase name="test66" classname="com.mycompany.solucao1.GestorDesportivo_ESTest" time="0.001"/>
  <testcase name="test21" classname="com.mycompany.solucao1.GestorDesportivo_ESTest" time="0.002"/>
  <testcase name="test65" classname="com.mycompany.solucao1.GestorDesportivo_ESTest" time="0.001"/>
  <testcase name="test20" classname="com.mycompany.solucao1.GestorDesportivo_ESTest" time="0.002"/>
  <testcase name="test64" classname="com.mycompany.solucao1.GestorDesportivo_ESTest" time="0">
    <failure message="expected:&lt;1&gt; but was:&lt;107&gt;" type="java.lang.AssertionError"><![CDATA[java.lang.AssertionError: expected:<1> but was:<107>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.mycompany.solucao1.GestorDesportivo_ESTest.test64(GestorDesportivo_ESTest.java:881)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:750)
]]></failure>
  </testcase>
  <testcase name="test29" classname="com.mycompany.solucao1.GestorDesportivo_ESTest" time="0.001">
    <system-out><![CDATA[Ok

]]></system-out>
  </testcase>
  <testcase name="test28" classname="com.mycompany.solucao1.GestorDesportivo_ESTest" time="0.001">
    <system-out><![CDATA[Ok

]]></system-out>
  </testcase>
  <testcase name="test63" classname="com.mycompany.solucao1.GestorDesportivo_ESTest" time="0.001">
    <failure message="expected:&lt;1&gt; but was:&lt;117&gt;" type="java.lang.AssertionError"><![CDATA[java.lang.AssertionError: expected:<1> but was:<117>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.mycompany.solucao1.GestorDesportivo_ESTest.test63(GestorDesportivo_ESTest.java:873)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:750)
]]></failure>
  </testcase>
  <testcase name="test62" classname="com.mycompany.solucao1.GestorDesportivo_ESTest" time="0.001">
    <failure message="expected:&lt;1&gt; but was:&lt;118&gt;" type="java.lang.AssertionError"><![CDATA[java.lang.AssertionError: expected:<1> but was:<118>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.mycompany.solucao1.GestorDesportivo_ESTest.test62(GestorDesportivo_ESTest.java:864)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:750)
]]></failure>
  </testcase>
  <testcase name="test61" classname="com.mycompany.solucao1.GestorDesportivo_ESTest" time="0.001">
    <failure message="expected:&lt;1&gt; but was:&lt;119&gt;" type="java.lang.AssertionError"><![CDATA[java.lang.AssertionError: expected:<1> but was:<119>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.mycompany.solucao1.GestorDesportivo_ESTest.test61(GestorDesportivo_ESTest.java:855)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:750)
]]></failure>
  </testcase>
  <testcase name="test60" classname="com.mycompany.solucao1.GestorDesportivo_ESTest" time="0.001">
    <failure message="expected:&lt;1&gt; but was:&lt;120&gt;" type="java.lang.AssertionError"><![CDATA[java.lang.AssertionError: expected:<1> but was:<120>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.mycompany.solucao1.GestorDesportivo_ESTest.test60(GestorDesportivo_ESTest.java:846)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:750)
]]></failure>
  </testcase>
</testsuite>