/*
 * This file was automatically generated by EvoSuite
 * Wed Jun 04 19:50:06 GMT 2025
 */

package com.mycompany.solucao1;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.mycompany.solucao1.UtilizadorAmador;
import java.time.Clock;
import java.time.LocalDate;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.time.MockClock;
import org.evosuite.runtime.mock.java.time.MockLocalDate;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, useJEE = true) 
public class UtilizadorAmador_ESTest extends UtilizadorAmador_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      LocalDate localDate0 = MockLocalDate.ofEpochDay(1);
      UtilizadorAmador utilizadorAmador0 = new UtilizadorAmador("zyfa`Ak?:P", "zyfa`Ak?:P", "zyfa`Ak?:P", 1, 1122, 1122, localDate0, 'v');
      LocalDate localDate1 = MockLocalDate.now();
      Object object0 = utilizadorAmador0.utilizadorNumPeriodo(localDate0, localDate1);
      assertNotSame(object0, utilizadorAmador0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      UtilizadorAmador utilizadorAmador0 = new UtilizadorAmador("Bh1hbF7", "Bh1hbF7", (String) null, 0, 0, 7, (LocalDate) null, '/');
      // Undeclared exception!
      try { 
        utilizadorAmador0.toString();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.mycompany.solucao1.Utilizador", e);
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      UtilizadorAmador utilizadorAmador0 = new UtilizadorAmador("", "8", "", (-655), 0, 1, (LocalDate) null, '1');
      Object object0 = utilizadorAmador0.clone();
      // Undeclared exception!
      try { 
        utilizadorAmador0.equals(object0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.mycompany.solucao1.Utilizador", e);
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      UtilizadorAmador utilizadorAmador0 = null;
      try {
        utilizadorAmador0 = new UtilizadorAmador((UtilizadorAmador) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.mycompany.solucao1.Utilizador", e);
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      UtilizadorAmador utilizadorAmador0 = new UtilizadorAmador();
      Clock clock0 = MockClock.systemUTC();
      LocalDate localDate0 = MockLocalDate.now(clock0);
      UtilizadorAmador utilizadorAmador1 = new UtilizadorAmador(utilizadorAmador0, localDate0, localDate0);
      assertEquals("", utilizadorAmador1.getNome());
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      UtilizadorAmador utilizadorAmador0 = new UtilizadorAmador();
      boolean boolean0 = utilizadorAmador0.equals((Object) null);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      UtilizadorAmador utilizadorAmador0 = new UtilizadorAmador();
      boolean boolean0 = utilizadorAmador0.equals(utilizadorAmador0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      UtilizadorAmador utilizadorAmador0 = new UtilizadorAmador();
      boolean boolean0 = utilizadorAmador0.equals("Utilizador\nCodigo de Utilizador: 0\nNome: \nMorada: \nEmail: \nFrequencia Cardiaca: 0 bpm\nPeso: 0.0 kilos\nAltura: 0 centimetros\nData de nascimento 14/02/2014\nIdade: 0 anos\nGenero: \u0000\nAtividades: \n\nPlanos de treino: \n\nTipo de Utilizador: Amador\n");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      UtilizadorAmador utilizadorAmador0 = new UtilizadorAmador();
      String string0 = utilizadorAmador0.toString();
      assertEquals("Utilizador\nCodigo de Utilizador: 0\nNome: \nMorada: \nEmail: \nFrequencia Cardiaca: 0 bpm\nPeso: 0.0 kilos\nAltura: 0 centimetros\nData de nascimento 14/02/2014\nIdade: 0 anos\nGenero: \u0000\nAtividades: \n\nPlanos de treino: \n\nTipo de Utilizador: Amador\n", string0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      UtilizadorAmador utilizadorAmador0 = new UtilizadorAmador("", "8", "", (-655), 0, 1, (LocalDate) null, '1');
      double double0 = utilizadorAmador0.getFatorMultiplicativo();
      assertEquals(1.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      UtilizadorAmador utilizadorAmador0 = new UtilizadorAmador("", "", "", 0, (-4441), (-4441), (LocalDate) null, 'v');
      UtilizadorAmador utilizadorAmador1 = new UtilizadorAmador(utilizadorAmador0);
      assertEquals("", utilizadorAmador1.getNome());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      UtilizadorAmador utilizadorAmador0 = new UtilizadorAmador("", "", "", 0, (-4441), (-4441), (LocalDate) null, 'v');
      // Undeclared exception!
      try { 
        utilizadorAmador0.utilizadorNumPeriodo((LocalDate) null, (LocalDate) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // date
         //
         verifyException("java.util.Objects", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      LocalDate localDate0 = MockLocalDate.ofEpochDay((-156L));
      UtilizadorAmador utilizadorAmador0 = null;
      try {
        utilizadorAmador0 = new UtilizadorAmador((UtilizadorAmador) null, localDate0, localDate0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.mycompany.solucao1.Utilizador", e);
      }
  }
}
